--- #YAML:1.0
name:                Tk-GraphItems
version:             0.12
abstract:            Display relation-graphs on a Tk::Canvas
license:             perl
author:              
    - Ch.Lamprecht <ch.l.ngre@online.de>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Scalar::Util:                  1.1
    Tk:                            804.027
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
