# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-GraphItems
version:      0.08
version_from: lib/Tk/GraphItems.pm
installdirs:  site
requires:
    Scalar::Util:                  1.1
    Tk:                            804.027

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
