# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-GraphItems
version:      0.01
version_from: lib/Tk/GraphItems.pod
installdirs:  site
requires:
    Tk:                            8.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
